openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-azure-postgresql
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          properties:
            domain_suffix:
              description: |
                Specify the domain suffix for the PostgreSQL Flexible Server. If not specified, it will generate a default domain suffix.
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 1
            resource_group:
              description: |
                Specify the resource group for the PostgreSQL Flexible Server. If not specified, it will generate a default resource group and domain suffix.
              title: Resource Group
              type: string
              x-walrus-ui:
                order: 1
            subnet:
              description: |
                Specify the subnet for the PostgreSQL Flexible Server. If not specified, it will generate a default subnet.
              title: Subnet
              type: string
              x-walrus-ui:
                order: 3
            virtual_network:
              description: |
                Specify the virtual network for the PostgreSQL Flexible Server. If not specified, it will generate a default virtual network and subnet.
              title: Virtual Network
              type: string
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version of the PostgreSQL Flexible Server to use. Possible values are 11.0, 12.0, 13.0, 14.0, 15.0, and 16.0.
          default: "16.0"
          enum:
          - "11.0"
          - "12.0"
          - "13.0"
          - "14.0"
          - "15.0"
          - "16.0"
          x-walrus-ui:
            group: Basic
            order: 5
        database:
          title: Database
          type: string
          description: "Specify the database name. The database name must be 2-64
            characters long and start with any lower letter, combined with number,
            or symbols: - _. \nThe database name cannot be PostgreSQL forbidden keyword.\n"
          default: mydb
          x-walrus-ui:
            group: Basic
            order: 5
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 1-63 characters long and start with lower letter, combined with number.
            The username cannot be PostgreSQL forbidden keyword and azure_superuser, admin, administrator, root, guest or public.
          default: rdsuser
          x-walrus-ui:
            group: Basic
            order: 6
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-128 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          writeOnly: true
          minLength: 8
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 7
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
            The computing resource design of Azure Cloud is very complex, it also needs to consider on the storage resource, please view the specification document for more information.
            For example: B_Standard_B1ms, GP_Standard_D2s_v3, MO_Standard_E4s_v3.
            See https://docs.microsoft.com/en-us/azure/postgresql/concepts-pricing-tiers for more information.
          default:
            class: B_Standard_B1ms
          properties:
            class:
              default: B_Standard_B1ms
              description: |
                Specify the pricing tier for the PostgreSQL Flexible Server. For example: B_Standard_B1ms, GP_Standard_D2s_v3, MO_Standard_E4s_v3. See https://docs.microsoft.com/en-us/azure/postgresql/concepts-pricing-tiers for more information.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          default:
            size: 32768
          properties:
            size:
              default: 32768
              description: |
                Specify the storage size of the PostgreSQL Flexible Server. The storage size is in megabytes.
              title: Size
              type: number
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
